### ISSUE TITLE
Error on check of structured text file with use of enum members

### ISSUE THREAD

**Issue by bitkeeper** [ironplc/ironplc#255]
**Describe the bug**
When using a enum type member it isn't an allowed value.

```ST
TYPE
    MyColors: (Red, Green);
END_TYPE

FUNCTION_BLOCK FB_EXAMPLE
    VAR
        Color: MyColors := Red;
    END_VAR
    Color := Green; (* This isn't allowed; undefined variable *)
END_FUNCTION_BLOCK
```

**To Reproduce**

1. Save the above example as test.st:
2. Run:
`ironplc check ./test.st`
3. Output:
```
error[P0015]: Variable not defined before used (variable=Green)
   ┌─ \\?\C:\data\work\staruml\statemachinegenerator\out\test.st:10:14
   │
10 │     Color := Green;
   │              ^^^^^ Undefined variable

Error: "Error during analysis"
```
**Expected behavior**
That the check passes like:
```
OK
```
**System**
 - Version: 0.66.0
 - OS: Windows 11
 - Distribution: Installer

**Comment by garretfick** [comment]
Thank you for reporting the issue.

The issue does look genuine given the data provided although I haven't yet tried to reproduce the issue. I will look into the cause and if it is genuine, I'll fix in an upcoming release. Releases normally happen every Monday.

Lastly, a word of caution. IronPLC's semantic analysis is nascent. You are likely to find additional issues. Further reports are very much appreciated.
________________________________
From: Bitlab ***@***.***>
Sent: Thursday, June 27, 2024 10:30:22 AM
To: ironplc/ironplc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ironplc/ironplc] Error on check of structured text file with use of enum members (Issue #255)


Describe the bug
When using a enum type member it isn't an allowed value.

TYPE
    MyColors: (Red, Green);
END_TYPE

FUNCTION_BLOCK FB_EXAMPLE
    VAR
        Color: MyColors := Red;
    END_VAR
    Color := Green; (* This isn't allowed; undefined variable *)
END_FUNCTION_BLOCK

To Reproduce
Steps to reproduce the behavior:

  1.  Save the above example as test.st:
  2.  Run:
ironplc check ./test.st
  3.  Output:

error[P0015]: Variable not defined before used (variable=Green)
   ┌─ \\?\C:\data\work\staruml\statemachinegenerator\out\test.st:10:14
   │
10 │     Color := Green;
   │              ^^^^^ Undefined variable

Error: "Error during analysis"


Expected behavior
That the check passes like:

OK


System

  *   Version: 0.66.0
  *   OS: Windows 11
  *   Distribution: Installer

**Comment by garretfick** [comment]
I have reproduced the error. The problem is that by the time semantic analysis gets this far, it thinks that the value is a variable name instead of an enumeration value.

**Comment by garretfick** [comment]
The problem is the parser - doesn't implement expression_value as a possible type.

**Comment by garretfick** [comment]
Fixing this is turning out to be more complex and I've had less free time than hoped over the weekend. This remains my top item to fix.

**Comment by garretfick** [comment]
I have hacked in a fix. The real problem is that I need to build a real symbol table to determine the type of each ambiguous item. That's a way off hence the hacked in fix.

I've kicked off a build so this should be the current release shortly.

**Comment by bitkeeper** [comment]
Thanks for the quick fix!
